import {parseYarnLockFile, parsePnpmLockFile} from '../src/lockFile'
import {expect, test} from '@jest/globals'

test('yarn lockfile parse', () => {
  const text = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


"@rails/actioncable@6.1.5":
  version "6.1.5"
  resolved "https://registry.yarnpkg.com/@rails/actioncable/-/actioncable-6.1.5.tgz#c24ec8123a8e7e239ceabda29078df9c93752394"
  integrity sha512-bV4/Q7NweGFm7t3GvUFm19UF2WKmcvlOXy7AxMWEZCwDxQLagAXhUpKb1AJ6Rg88cPHqXSQHaGKr84lIMd607A==

bootstrap@^3.3:
  version "3.4.1"
  resolved "https://registry.yarnpkg.com/bootstrap/-/bootstrap-3.4.1.tgz#c3a347d419e289ad11f4033e3c4132b87c081d72"
  integrity sha512-yN5oZVmRCwe5aKwzRj6736nSmKDX7pLYwsXiCj/EYmo16hODaBiT4En5btW/jhBF/seV+XMx3aYwukYC3A49DA==

jquery@^3.5.1:
  version "3.6.0"
  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.6.0.tgz#c72a09f15c1bdce142f49dbf1170bdf8adac2470"
  integrity sha512-JVzAR/AjBvVt2BmYhxRCSYysDsPcssdmTFnzyLEts9qNwmjmu4JTAMYubEfwVOSwpQ1I1sKKFcxhZCI2buerfw==
`

  const pkgs = parseYarnLockFile(text)
  expect(pkgs.size).toEqual(3)
  expect(pkgs.has('@rails/actioncable')).toBeTruthy()
  expect(pkgs.has('bootstrap')).toBeTruthy()
  expect(pkgs.has('jquery')).toBeTruthy()
})

test('pnpm@v5 lockfile parse', () => {
  const text = `lockfileVersion: 5.4

specifiers:
  '@popperjs/core': ^2.11.5
  bootstrap: ^5.1.3

dependencies:
  '@popperjs/core': 2.11.5
  bootstrap: 5.1.3_@popperjs+core@2.11.5

devDependencies:

packages:
  /@popperjs/core/2.11.5:
    resolution: {integrity: sha512-9X2obfABZuDVLCgPK9aX0a/x4jaOEweTTWE2+9sr0Qqqevj2Uv5XorvusThmc9XGYpS9yI+fhh8RTafBtGposw==}

  /bootstrap/5.1.3_@popperjs+core@2.11.5:
    resolution: {integrity: sha512-fcQztozJ8jToQWXxVuEyXWW+dSo8AiXWKwiSSrKWsRB/Qt+Ewwza+JWoLKiTuQLaEPhdNAJ7+Dosc9DOIqNy7Q==}
    peerDependencies:
      '@popperjs/core': ^2.10.2
    dependencies:
      '@popperjs/core': 2.11.5
    dev: false
`

  const pkgs = parsePnpmLockFile(text)
  expect(pkgs.size).toEqual(2)
  expect(pkgs.has('bootstrap')).toBeTruthy()
  expect(pkgs.has('@popperjs/core')).toBeTruthy()
})

test('pnpm@v9 lockfile parse', () => {
  const text = `lockfileVersion: '9.0'
settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:

  .:
    dependencies:
      bootstrap:
        specifier: ^5.3.3
        version: 5.3.3(@popperjs/core@2.11.8)

packages:

  '@popperjs/core@2.11.8':
    resolution: {integrity: sha512-P1st0aksCrn9sGZhp8GMYwBnQsbvAWsZAX44oXNNvLHGqAOcoVxmjZiohstwQ7SqKnbR47akdNi+uleWD8+g6A==}

  bootstrap@5.3.3:
    resolution: {integrity: sha512-8HLCdWgyoMguSO9o+aH+iuZ+aht+mzW0u3HIMzVu7Srrpv7EBBxTnrFlSCskwdY1+EOFQSm7uMJhNQHkdPcmjg==}
    peerDependencies:
      '@popperjs/core': ^2.11.8

snapshots:

  '@popperjs/core@2.11.8': {}

  bootstrap@5.3.3(@popperjs/core@2.11.8):
    dependencies:
      '@popperjs/core': 2.11.8
`

  const pkgs = parsePnpmLockFile(text)
  expect(pkgs.size).toEqual(2)
  expect(pkgs.has('bootstrap')).toBeTruthy()
  expect(pkgs.has('@popperjs/core')).toBeTruthy()
})
