import {YarnLockFile} from '../src/yarnlock'
import {expect, test} from '@jest/globals'

test('parse', () => {
  const text = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


bootstrap@^3.3:
  version "3.4.1"
  resolved "https://registry.yarnpkg.com/bootstrap/-/bootstrap-3.4.1.tgz#c3a347d419e289ad11f4033e3c4132b87c081d72"
  integrity sha512-yN5oZVmRCwe5aKwzRj6736nSmKDX7pLYwsXiCj/EYmo16hODaBiT4En5btW/jhBF/seV+XMx3aYwukYC3A49DA==

jquery@^3.5.1:
  version "3.6.0"
  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.6.0.tgz#c72a09f15c1bdce142f49dbf1170bdf8adac2470"
  integrity sha512-JVzAR/AjBvVt2BmYhxRCSYysDsPcssdmTFnzyLEts9qNwmjmu4JTAMYubEfwVOSwpQ1I1sKKFcxhZCI2buerfw==
`

  const lockfile = YarnLockFile.parse(text)
  expect(lockfile).toBeTruthy()

  const pkgs = lockfile.installedPackages()
  expect(pkgs.size).toEqual(2)
  expect(pkgs.has('bootstrap')).toBeTruthy()
  expect(pkgs.has('jquery')).toBeTruthy()
})
